### ISSUE TITLE
CSV Files

### ISSUE THREAD

**Issue by Abdullah2993** [FICTURE7/CoCSharp#1]
Can you please provide the link to the csv files? They are removed from the cocdp

**Comment by FICTURE7** [comment]
Sure [here](https://www.dropbox.com/s/ygrrow188az1vg3/database.rar?dl=0) extract them in a folder called "database", in the same folder as the program is running. Maybe we could add a feature to the proxy that will download the files from the official CoC servers and then use them instead?

**Comment by Abdullah2993** [comment]
Thanks and that would be really nice.
