### ISSUE TITLE
Encryption Inconsistant

### ISSUE THREAD

**Issue by FICTURE7** [FICTURE7/CoCSharp#13]
Encryption is failing sometimes because of async networking.

**Comment by castelbuilder123** [comment]
you could add a packet buffer for this. when you await a encryption update packet wait until it arrives and put all packets with the new encryption in the buffer and process it later. for detecting encryption fails check the packets if they match the protocol (is it a valid packet id, could this packet id be received at this time)

**Comment by FICTURE7** [comment]
Yeah, I was doing something close to your solution.

**Comment by FICTURE7** [comment]
Well, I did some debugging turns out the problem is TCP packet fragmentation. I am currently working on a fix and improving buffer management to reduce memory fragmentation.
