### ISSUE TITLE
Add client scripting api (c# dll, lua)

### ISSUE THREAD

**Issue by castelbuilder123** [FICTURE7/CoCSharp#17]
Add a scripting api to the client.

For C# create a dll which communicates over localhost:xxxxx with the client, add functions for each packet and add a forwarder to lan so you can remotly control the client

For Lua just use a lua interpreter which can be controller per cli and per network, if forwarded

Checklist:

- [x] Plugins
- [ ] Network
- [ ] Lua

**Comment by FICTURE7** [comment]
We will use .NET for the plugin API and we probably won't use a network because it will be a pain in the butt to implement it that way.

You can start to work on it, am focusing on CoCSharp it self at the moment.

**Comment by castelbuilder123** [comment]
well i created enough network remotes that i know what i am doing :+1:

**Comment by FICTURE7** [comment]
Yeah, but its the problem here.

Using a network for a plugin API would be extremely dumb.
It reduces speed and performance of the whole thing and the developer of the script can't run the code he wants.

Using networks is a waste of time and effort.

**Comment by castelbuilder123** [comment]
well we could do both, plugins for expandable functionality (eg clan search etc) and a network api for bots, etc

**Comment by FICTURE7** [comment]
If someone wants to add a web API to the thing, they could just use the plugin API.

**Comment by FICTURE7** [comment]
And am not trying to remake BlackElixir by the way...

**Comment by castelbuilder123** [comment]
no not that kind of search, something to search clans automaticly by its name and one of his members names.

**Comment by FICTURE7** [comment]
If you really want it then, when the plugin API is up, you could write a plugin for this.

**Comment by castelbuilder123** [comment]
Comments/Suggestions?

namespace CoCSharp.Client.Api
{
    interface IPlugin
    {
        string Name { get; set; }
        string Desc { get; set; }
        string Author { get; set; }
        List<string> Dependencies { get; set; }

        //Livecycle:
        void preInit();
        void Init();
        void postInit();
        void update(); // Called every 100 ms
        void onCmdRecv(string cmd, string[] param);
        void preDeInit();
        void DeInit();
        void postDeInit(); 
    }
}

**Comment by FICTURE7** [comment]
Follow the naming convention please and "CoCSharp.Client.Api" should be "CoCSharp.Client.API"
I don't think that the base plugin class should an interface, it should be an abstract.
I don't really like the "Init" thing. Use "OnStart" and name names close to this.

**Comment by FICTURE7** [comment]
Should I create a new branch for this? 
That way I'll be able to modify or add stuff to the thing.

**Comment by castelbuilder123** [comment]
i will leave this decision up to you

**Comment by FICTURE7** [comment]
I don't think we need a Lua or a "network" API.
Recreating issue

**Comment by FICTURE7** [comment]
Reopened here #24
