### ISSUE TITLE
Fetch CSV files from official CoC server

### ISSUE THREAD

**Issue by FICTURE7** [FICTURE7/CoCSharp#2]

**Comment by Abdullah2993** [comment]
CSV files are fetched over HTTP or the COCProtocol?

**Comment by Abdullah2993** [comment]
IMHO the csv files can't be downloaded from the server but they can be extracted from the APK
![2015-06-30_23-00-17](https://cloud.githubusercontent.com/assets/5978905/8437940/db3f8e02-1f7b-11e5-847c-b86484474ffa.png)

**Comment by FICTURE7** [comment]
According [cocdp](https://github.com/clanner/cocdp/wiki/Servers) all of CoC's assets are stored [here](http://b46f744d64acd2191eda-3720c0374d47e9a0dd52be4d281c260f.r11.cf2.rackcdn.com/), and fingerprint's hash is the root of the asset folder. In the [LoginRequestPacket](https://github.com/FICTURE7/CoCSharp/blob/master/CoCSharp/Networking/Packets/LoginRequestPacket.cs) the FingerprintHash is sent, so we could use this. :]

**Comment by Abdullah2993** [comment]
@FICTURE7 didn't read that earlier. This is a more convenient method :)
