### ISSUE TITLE
CoCSharp.Client Plugin API

### ISSUE THREAD

**Issue by FICTURE7** [FICTURE7/CoCSharp#24]
Just a simple working plugin API. Ideas can be discussed here.

**Comment by castelbuilder123** [comment]
we should bring back a pluginapi class, for things like joining a clan or upgrading buildings or training troops

**Comment by FICTURE7** [comment]
It shouldn't be problem just use the Client class.

**Comment by castelbuilder123** [comment]
i will add a complete village interaction via plugins, as far as possible (limited by CoCSharp)

**Comment by FICTURE7** [comment]
I think you didn't read the code that handles CSV files or any other code at all or you did not even understand them because from what I can see your skills at writing C# code is fairly poor.

**Comment by castelbuilder123** [comment]
yeah i read them afterwards. and my skill is poor because im 15 and havent learnt c# from someone, just by myself

**Comment by FICTURE7** [comment]
lel, am 15 also

**Comment by FICTURE7** [comment]
and learnt by myself

**Comment by FICTURE7** [comment]
well, this explains why u always have an excuse to everything lel

**Comment by FICTURE7** [comment]
and u would be surprised by how old i am ;]

**Comment by castelbuilder123** [comment]
well tell me?

**Comment by FICTURE7** [comment]
Lets keep personal stuff out this. 
But I'll tell you that my age is extremely close to yours.

**Comment by castelbuilder123** [comment]
16 :D or am i getting colder?

**Comment by FICTURE7** [comment]
Anyways, do you think there is more to add to the API?

**Comment by castelbuilder123** [comment]
first we should modify the logic of cocsharp, like adding building type enum to buildings

**Comment by FICTURE7** [comment]
We don't need to, this data is specified in .csv files.

**Comment by FICTURE7** [comment]
Botting with the client won't be possible as we don't know how the checksum works by the way.

**Comment by castelbuilder123** [comment]
it would be nicer if the csv files get parsed automaically and the information is accessable

**Comment by FICTURE7** [comment]
Well, I implemented the parsing part.

**Comment by FICTURE7** [comment]
Take a look [here](https://github.com/FICTURE7/CoCSharp/tree/plugin-api/CoCSharp/Data/Csv).

**Comment by castelbuilder123** [comment]
what checksum do you mean?

**Comment by castelbuilder123** [comment]
at the login packet?

**Comment by FICTURE7** [comment]
No, at ClientCommandPacket

**Comment by FICTURE7** [comment]
You should get yourself some info before you talk xD

**Comment by castelbuilder123** [comment]
yeah

**Comment by castelbuilder123** [comment]
well i am too lazy to look at the clientcommandpacket, so does the checksum change? per start or per update or every time?

**Comment by FICTURE7** [comment]
Laziness is not what I want. Go find out yourself.

**Comment by castelbuilder123** [comment]
nope :p

**Comment by FICTURE7** [comment]
pfff, I don't know why am I even wasting my time with you.

**Comment by castelbuilder123** [comment]
i dont know too :tongue:

**Comment by castelbuilder123** [comment]
l3l
