### ISSUE TITLE
Plugin-API events

### ISSUE THREAD

**Issue by castelbuilder123** [FICTURE7/CoCSharp#27]
make a better event framework, for instance: events can be canceled and event priority.
the following functions should be added to events:
event.isCancelled()
event.setCannceled(bool)

also the plugin should implement a listener class for events:
public class ChatEvents : Listener {
[EventHandler(Priority=PriorityEnum.HIGHEST)]
public void onRecvHigh(ChatMsgRecvEvent evt)
{
evt.setCancelled(true);
}
[EventHandler(Priority=PriorityEnum.LOWEST)]
public void onRecvLow(ChatMsgRecvEvent evt)
{
// should not be called because the event is cancelled
Console.WriteLine("msg recv");
}
}

**Comment by FICTURE7** [comment]
copied from bukkit?

**Comment by castelbuilder123** [comment]
nope forge and bukkit

**Comment by castelbuilder123** [comment]
and why are you closing this instant

**Comment by FICTURE7** [comment]
Cause the client is not my main point of interest.

**Comment by castelbuilder123** [comment]
but mine :D

**Comment by castelbuilder123** [comment]
and remember im lazy :D

**Comment by FICTURE7** [comment]
Well you're probably the stupidest person I have ever met on the internet.
I don't give a single f about you. You try to act clever and shit but you ain't.

**Comment by FICTURE7** [comment]
I don't get paid to work on this project. I do what I want to.

**Comment by castelbuilder123** [comment]
thats was just me making fun you know? remember if i make a joke im writing :D behind it

**Comment by FICTURE7** [comment]
I don't care anymore cause you're annoying and a waste of time.
