### ISSUE TITLE
MEF for Plugins?

### ISSUE THREAD

**Issue by cfHxqA** [FICTURE7/CoCSharp#28]
Hello!, why do not you use MEF for the extensions? That's from the implementation much easier and faster with the initialization of the extensions. :)

https://msdn.microsoft.com/en-us/library/dd460648(v=vs.110).aspx

**Comment by FICTURE7** [comment]
Owhhh, never heard of that! I will take a look at it tomorrow. Thanks :]

**Comment by FICTURE7** [comment]
I can't really find any advantage of using MEF instead of our current implementation. If there is any you can find, go ahead and list them. =]
