### ISSUE TITLE
Command? How to send it?

### ISSUE THREAD

**Issue by cfHxqA** [FICTURE7/CoCSharp#29]
Hello, already see how to send packets... but how can ill send commands to server?

**Comment by FICTURE7** [comment]
Well, you can't unless you know how to calculate the checksum in [ClientCommandPacket](https://github.com/FICTURE7/CoCSharp/blob/master/CoCSharp/Networking/Packets/ClientCommandPacket.cs)

**Comment by FICTURE7** [comment]
If you really want to send a command packet you could try something like this

```c#
Client.QueuePacket(new ClientCommandPacket()
{
    Subtick = 0,
    Checksum = theChecksum,
    Commands = new ICommand[]
    {
        new BuyDecorationCommand()
        {
            X = 0,
            Y = 0,
            DecorationID = decorationId,
            Unknown1 = 0
        }
    }
});
```
