### ISSUE TITLE
Handle Packet 24338 - Clan Wars Logs

### ISSUE THREAD

**Issue by circa94** [FICTURE7/CoCSharp#33]
This Packet contains the clan wars logs and has to implemented

**Comment by FICTURE7** [comment]
I implemented the packet as [AllianceWarLogPacket](https://github.com/FICTURE7/CoCSharp/blob/master/CoCSharp/Networking/Packets/AllianceWarLogPacket.cs). Could check if it works on your account?

**Comment by circa94** [comment]
You just renamed the class an its propteries or?

**Comment by FICTURE7** [comment]
The class name, just to follow the style and pattern.

**Comment by FICTURE7** [comment]
I guess we can close this?

**Comment by circa94** [comment]
Sure thank you :)
