### ISSUE TITLE
Handle Packet 24324 - ClanDescription

### ISSUE THREAD

**Issue by circa94** [FICTURE7/CoCSharp#36]
It seams that this packet contains only the clan description

**Comment by FICTURE7** [comment]
I'll start implementing this packet.

This packet seems that it is sent just after the login sequence.
It is sent only for the user's clan and if you got more packet samples send me them. :]

**Comment by FICTURE7** [comment]
You could also give info about your clan like members count, level etc.

**Comment by FICTURE7** [comment]
Take a look [here](https://github.com/FICTURE7/CoCSharp/blob/master/CoCSharp/Networking/Packets/ClanDescriptionPacket.cs), if you have any suggestions go ahead. :]

**Comment by circa94** [comment]
![clandesc](https://cloud.githubusercontent.com/assets/6034570/10223915/c69226b2-685b-11e5-9310-b9fb4d977142.PNG)


is not working for me correctly. i will figure it out

**Comment by FICTURE7** [comment]
Ok, if you can't figure it out, just send me the packet dumps and I'll what I can do.

**Comment by circa94** [comment]
I got this stuff :)
-----------------------

00 00 00 89 -> Descrition Length

61 62 20 4C 76 6C 20 36 30 20 2D 20 43 57 20 32 20 6D 61 6C 20 64 69 65 20 57 6F 63 68 65 20 28 44 69 2D 44 6F 20 26 20 46 72 2D 53 6F 29 20 2D 20 57 61 70 70 65 6E 70 66 6C 69 63 68 74 20 61 62 20 32 20 54 61 67 65 20 6E 61 63 68 20 53 61 69 73 6F 6E 62 65 67 69 6E 6E 20 2D 20 53 70 65 6E 64 65 6E 76 65 72 68 C3 A4 6C 74 6E 69 73 20 31 3A 33 20 20 2D 20 6A 65 64 65 72 20 4B C3 A4 6D 70 66 74 20 6D 69 74 21      
^------Description                                                      

00 00 00 05 |
00 00 00 00 |
01 00 00 00 |
4A 00 12 CF |----- Unknown...
4F 00 00 00 |
22 00 16 C4 |
88 00 00 00 |

0D 44 61 72 6B 44 61 6E 67 65 72 41 24 24 | -> Clan Name

60 00 1A 55 | -> 1610619477 ?
00 00 00 02 | -> 2 -> invite Only?
00 00 00 16 | -> 22 members
00 00 38 00 | -> Trophies
00 00 00 00 | -> 0 min trophies
00 00 00 11 | -> wins
00 00 00 29 | -> losts
00 00 00 02 | -> draws
00 1E 84 82 | -> 2000002 -> some id
00 00 00 02 | -> 2
01 E8 48 5E | -> 32000094 -> ?
00 00 03 FA | -> CLan EP
00 00 00 04 | -> Clan Level

**Comment by FICTURE7** [comment]
Just upload the packet dumps in "packet_dumps" folder, it will easier for me.

**Comment by FICTURE7** [comment]
I think I fixed it. The problem was probably because of the string which it did not read. Thanks! :]

**Comment by circa94** [comment]
Cool :)

**Comment by FICTURE7** [comment]
Should I close the issue?

**Comment by circa94** [comment]
Your Implementation is not working for me. So i have coding some additional stuff for it

**Comment by FICTURE7** [comment]
hmmm, I see, but can't you send me your packet dumps so that we can find a working solution?

**Comment by circa94** [comment]
Okay i will send you the dump. Which program are you using for open the dump files?

**Comment by FICTURE7** [comment]
Any hex editor should do it, like HxD.

**Comment by circa94** [comment]
Okay thank you

**Comment by FICTURE7** [comment]
So are you sending me them?

**Comment by circa94** [comment]
yes sorry i was not at the pc.  i thought i have found my mistake. but you can also have a look

**Comment by circa94** [comment]
where can i send you the file?

**Comment by FICTURE7** [comment]
You can send me them on github by using this function. 
![:)](https://cloud.githubusercontent.com/assets/8182340/10245792/fa268a2a-691b-11e5-96a2-a3eccf5f6aa3.PNG)

**Comment by circa94** [comment]
Unfortunately, we don’t support that file type.  Dateien auswählen Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, or PDF.

**Comment by circa94** [comment]
i have also looked inside the dump file and found the mistake. i will commit it

**Comment by FICTURE7** [comment]
Ok thanks! But could you send them via email or something? :]

**Comment by circa94** [comment]
add me in skype. that will be easier for the future :)

**Comment by FICTURE7** [comment]
I sent you a request
