### ISSUE TITLE
Handle Packet 24335 - LastClanWar

### ISSUE THREAD

**Issue by circa94** [FICTURE7/CoCSharp#37]
It seams that this packet contains all TroopRequests

**Comment by FICTURE7** [comment]
I don't seem to able to get a packet dump, could I you send me one or how do I make the server send me one?

**Comment by circa94** [comment]
i get this packet only on the first login and only when there are open troop requests in my clan. wait until your clan members are requesting and then restart the game. should come 2-4 packets after OwnHomeData

**Comment by circa94** [comment]
It seams that this packet holds data from the last cw
