### ISSUE TITLE
Log into existing account?

### ISSUE THREAD

**Issue by RMaron** [FICTURE7/CoCSharp#41]
Love this, by the way, now I can make my automation system. However, I have hit a wall in that I can't login to my pre-existing account. I've changed the udid and adid for the login packet, to my own, and even my mac address. It doesn't login as me, though. How would I go about doing this? Add documentation on this, I guess, would be the issue. Thanks, 
~Rob

**Comment by Baghe** [comment]
You need your UserID and Token which you can get with CoCSharp.Proxy and
Bluestacks.
Il 29/Ott/2015 12:07, "RMaron" <notifications@github.com> ha scritto:

**Comment by RMaron** [comment]
Thank you, I will try this when I get home.

**Comment by RMaron** [comment]
I have tried this, and I open Bluestacks after I run the proxy from visual studio. It doesn't log anything, though. Do I have to add this functionality?

**Comment by RMaron** [comment]
All it says is:
"Starting proxy...
CoC# is running on *:9339",

It does not log anything else when I open bluestacks, though. Thanks for the help.

**Comment by circa94** [comment]
You must let your bluestacks connect to your Computer where the proxy is running. Try host editor. You need a rooted version of bluestacks

**Comment by RMaron** [comment]
Alright, I connected to the proxy server via my phone by going to the wireless settings. It tells me that a lot of new socket connections are recieved, however, when I start the app, it doesn't work. Maybe it's not using port 9339 in this case?

**Comment by RMaron** [comment]
It successfully connects to the proxy server, however.

**Comment by RMaron** [comment]
I'm going to try rooting bluestacks now.

**Comment by circa94** [comment]
When you try it with your phone, you also need to root it and edit your host file with the APP host editor from the play store.

**Comment by RMaron** [comment]
Sorry for asking so many questions, but what do I have to edit in the hosts file?

**Comment by circa94** [comment]
You must tell clash of clans that it does not connect to the original server but to your Computer and then to the Server. 

So you had to set for the hostname: gamea.clashofclans.com and as IP you take your local IP address

**Comment by RMaron** [comment]
Thank you, it works!

**Comment by circa94** [comment]
You are welcome :)

**Comment by RMaron** [comment]
Sorry, one last thing; how do I capture it if there's a really long stream that takes up the window? It won't scroll up all the way to the beginning.

**Comment by circa94** [comment]
I have added a help guide in the wiki. Please see: https://github.com/FICTURE7/CoCSharp/wiki/CoCSharp.Client-Login-with-your-account

**Comment by FICTURE7** [comment]
Thank you for handling this @circa94 ^^
