### ISSUE TITLE
Dispose

### ISSUE THREAD

**Issue by FastFrench** [FICTURE7/CoCSharp#42]
I think it would be cleaner and safer if you would implement IDisposable for all your base classes that use Sockets or any other IDisposable objects (CoCClient, CoCProxy, and even loggers like ExceptionLogger in order to close the Stream). 
Also to favor good practices, maybe Plugin base class should be turned into IDisposable too.

**Comment by FICTURE7** [comment]
Thanks for pointing this out, I will try to implement it as soon as possible. :]
