### ISSUE TITLE
AllianceSearchResponsePacket never showing up

### ISSUE THREAD

**Issue by toniperic** [FICTURE7/CoCSharp#49]
I send packet AllianceSearchRequestPacket with `SearchString` set to `foobar`. It's logged and I can see it going from client > server in the packets.log file, but apparently I never see a response back in packets.log file. All I can see are the keepAlive packets every 5 seconds. 

[packets.txt](https://github.com/FICTURE7/CoCSharp/files/34019/packets.txt)

Anyone else experiencing this?

I'd like to get more info about my clan but I am unable to find the clan ID, so I've gone this route of performing a search first that would return the clan data.

**Comment by circa94** [comment]
I just implemented this without much testing. Normal it should work. You can find your Clan ID in every else packet with "alliance.." starting

**Comment by FICTURE7** [comment]
I dug around a bit, and found out that AllianceSearchResponsePacket is not the right packet to send to search for alliances but AllianceInfoRequestPacket. The current read/write implementation of AllianceInfoRequestPacket is incorrect. Thanks for opening the issue. ^^

**Comment by toniperic** [comment]
circa94 still couldn't find the clan ID. Could you provide an example?

Would be cool to search for other clans as well, not just my own.

**Comment by toniperic** [comment]
Thanks guys, I have managed to get it all working after the latest merged commit.

However I am now wondering is there a way in the library to fetch data such as player's achievements?

**Comment by FICTURE7** [comment]
At the moment, you can't because we are just reading the data, but not storing them.

**Comment by toniperic** [comment]
What a shame. Thanks for your response!
