### ISSUE TITLE
How to use the proxy?

### ISSUE THREAD

**Issue by Abdullah2993** [FICTURE7/CoCSharp#5]
How are you using the proxy?
Are you using Bluestacks?

**Comment by EdgeKiller** [comment]
You need to have visual studio. And you can use a rooted bluestacks or a rooted Android device with hosts editor.

**Comment by FICTURE7** [comment]
Yes, I am using a rooted version of Bluestacks and Visual Studio 2013. I used [Host Editor](https://play.google.com/store/apps/details?id=com.nilhcem.hostseditor) to edit gamea.clashofclans.com to my computer's local IP address(192.168.1.2) where the proxy server is running. You can play around with "proxyConfig.xml" to make other stuff.
