### ISSUE TITLE
Log.Save() & Log.Save(path) failing because it is being used by another process.

### ISSUE THREAD

**Issue by FICTURE7** [FICTURE7/CoCSharp#50]

**Comment by FastFrench** [comment]
I got this message when I used your lib to write a multiclient (several CoCClient-derived instances running at the same time): as the path for log files is hardcoded, they all try to write to the same file asynchronously and you get this kind of error. 
In my case, I prefixed the filename of logs with the id of the client, and it's now OK. 
Another solution would be to make the logger classes mutlithread-safe: make sure you don't let the file open (close each time you write something), and lock the ressource while writing.

**Comment by FICTURE7** [comment]
Yeah, I fixed this a couple of days ago but I haven't yet push my commits to GitHub.

**Comment by FICTURE7** [comment]
No longer supporting `master` branch so I guess I can close this.
