### ISSUE TITLE
Proxy stucks on login..

### ISSUE THREAD

**Issue by tc-maxx** [FICTURE7/CoCSharp#60]
Hi,

since the last update the proxy gets stuck on login :(
If the encryption changed again?

Thankz!
MaXX

**Comment by FICTURE7** [comment]
Must be something related to the public key being changed in every update. Updating [this](https://github.com/FICTURE7/CoCSharp/blob/rewrite/CoCSharp/Networking/Cryptography/Crypto8.cs#L45-L56) with the new public keys should fix it if the problem is related to the keys.
