### ISSUE TITLE
"Error code 9009" while compiling

### ISSUE THREAD

**Issue by ghost** [FICTURE7/CoCSharp#64]
Hello,
I am having PostBuild.exe 9009 error on windows. For those who have "The command "mono..blahblah" exited with code 9009.", first, run PostBuild.exe from solution folder > postbuild > bin > debug and then right click to CoCSharp > properties > Build Events and just clear Post-Build Event Command line textbox. That's it, error fixed :)

My solution might not be correct, so please fix this problem.
Thanks

**Comment by FICTURE7** [comment]
You must have `mono.exe` in your PATH to be able to run the post build but it should compile the stuff fine. Its just to copy the latest version of `libsodium.dll` to the compiled output directory of the CoCSharp library.
