### ISSUE TITLE
Proxy locking up

### ISSUE THREAD

**Issue by Poyser1911** [FICTURE7/CoCSharp#65]
Connects to server but stops there in the proxy

Done(68.6441ms)! Listening on *:9339
Accepted new client: [::ffff:192.168.0.106]:55741
Created new connection to gamea.clashofclans.com
Acting as server with standard
        public-key: 72f1a4a4c48e44da0c42310f800e96624e6dc6a641a9d41c3b5039d8dfadc27e
        private-key: 1891d401fadb51d25d3a9174d472a9f691a45b974285d47729c45c6538070d85
Acting as client with generated
        public-key: ff9d2ab6911d462f8e99a1a673165efd775ff9d34da8cf6b09f0b7bf8ef5e32c
        private-key: 8b1e13c8b316ad0bfd99fb3850d882db7601ecf3bbe10978cb2356ec7caf9569
SessionRequestMessage - 10100:
    Unknown1: 1
    Unknown2: 9
    MajorVersion: 8
    Unknown4: 0
    MinorVersion: 332
    Hash: "caf5869bc1270ec51ebf6bd89089182ee0650774"
    Unknown6: 2
    Unknown7: 2

SessionSuccessMessage - 20100:
    SessionKey: System.Byte[]

LoginRequestMessage - 10101:
    PublicKey: System.Byte[]
    SessionKey: System.Byte[]
    Nonce: System.Byte[]
    UserID: 1
    UserToken: "d9bcpp21iyln36lsbftvdfk4jn9ba73d9rprzjng"
    MajorVersion: 8
    ContentVersion: 0
    MinorVersion: 332
    MasterHash: "caf5869bc1270ec51ebf6bd89089182ee0650774"
    UDID: ""
    OpenUDID: "2256c375452209c4"
    MacAddress: null
    DeviceModel: "HUAWEI Y330-U05"
    LocaleKey: 2000000
    Language: "en"
    AdvertisingGUID: "583fc04c-28f5-4e3e-8569-1b5042937d3b"
    OSVersion: "4.2.2"
    Unknown2: 1
    Unknown3: ""
    AndroidDeviceID: "blahblah"
    FacebookDistributionID: ""
    IsAdvertisingTrackingEnabled: True
    VendorGUID: ""
    Seed: 228069849
    Unknown4: 2
    Unknown5: ""
    Unknown6: ""
    ClientVersion: "8.332.2"

```
    => Decrypted LoginRequestMessage with pk 7f8d2661ac94b8023bd3f70040df27c993b81875fb10674b34001d767d2e9151
    => Encrypted LoginRequestMessage with pk ff9d2ab6911d462f8e99a1a673165efd775ff9d34da8cf6b09f0b7bf8ef5e32c
```

**Comment by FICTURE7** [comment]
Might be because there has slight protocol changes during the last updates, going to fix it soon.

**Comment by Poyser1911** [comment]
oh ok ^^

**Comment by Poyser1911** [comment]
@FICTURE7 when? :( and is it possible for me to make a program to intercept and send like chat messages packets to the server? 

edit: and what about a replicated client like back in v7 ~>Is this possible to remake?

**Comment by FICTURE7** [comment]
It was going to be soon, but that was until I decided to remake a lot of the Logic stuff. xD
And for the client, it should be possible to remake but I not planning on doing that soon, the server is the priority for me right now.

**Comment by Poyser1911** [comment]
@FICTURE7 and what are the breif steps what one would need to do/learn to help in the remake? :D

**Comment by FICTURE7** [comment]
Hmmm, I don't really right now, but if you can write some code, you could try to port the old client code with to be compatible with the new library.

**Comment by FICTURE7** [comment]
I updated the proxy to 8.322.16, you might want to take a look into it again. Be sure to use the patched libg.so with the standard keys as well.

**Comment by Poyser1911** [comment]
@FICTURE7 i want u be like you
edit: what are the keys? 
this is my config.json i patched it with this, it seems no not be decrying the right because its all nulls
btw i edited to patcher to skip the checks, dunno why it needed to but yea it was a pain.
i dont have the dd and md5sum apps

shed some light over here please
{
  "debug": true,
  "package": "com.supercell.clashofclans",
  "key": "72f1a4a4c48e44da0c42310f800e96624e6dc6a641a9d41c3b5039d8dfadc27e",
 "url": "gamea.clashofclans.com",
  "keystore": {
   .....
  },
  "paths": {
    "apktool": "C:\apktool.bat",
    "md5sum": "C:\Users\Poyser\Downloads\md5sum.bat",
    "dd": "C:\dd.exe",
    "keytool": "C:\Program Files\Java\jdk1.7.0_79\bin\keytool.exe",
    "jarsigner": "C:\Program Files\Java\jdk1.7.0_79\bin\jarsigner.exe",
    "zipalign": "C:\Users\Poyser\AppData\Local\Android\sdk\build-tools\23.0.3\zipalign.exe"
  },
  "versions": {
  "8.332.16": {
    "key": " bb9ca4c6b52ecdb40267c3bcca03679201a403ef6230b9e488db949b58bc7479",
    "arm": {
      "md5": "caf5869bc1270ec51ebf6bd89089182ee0650774",
      "key-offset": "4431896",
      "url-offset": "3672818"
    },
    "x86": {
      "md5": "caf5869bc1270ec51ebf6bd89089182ee0650774",
      "key-offset": "6434840",
      "url-offset": "4973505"
    }
  }
}
}

**Comment by FICTURE7** [comment]
I'm using my own patcher to patch the apks, you could try to download that [one](https://www.dropbox.com/s/zpbabu6nj4la38h/Clash%20of%20Clans%208.322.16%20-%20Patched.apk?dl=1) and see if it works.
