### ISSUE TITLE
Stop on loading Screen After load complate

### ISSUE THREAD

**Issue by CoCEmu** [FICTURE7/CoCSharp#66]
hello,
i use client v 7.200.13 and cocsharp server - master
after complate loading screen game not started untile exiting game.
(master and rewrite)no work.
how can i fix this?

**Comment by FICTURE7** [comment]
I stopped supporting the `master` branch which supports 7.x.x. If you're using the `rewrite` branch' server which only supports 8.x.x you must have a patched .apk with the standard public keys, more info [here](https://github.com/clugh/coc-patcher).
