### ISSUE TITLE
ServerConfiguration causes NullReferenceException

### ISSUE THREAD

**Issue by DaividSmith** [FICTURE7/CoCSharp#89]
in last Commit i get this error
08a6de2
i get this error in run CoCSharp.Server.exe
line 27 in Server.cs
_config = new ServerConfiguration("config.xml");
pic:
http://imgur.com/a/TAUaL

**Comment by knightking10** [comment]
`cs
private static readonly ServerConfiguration _default =
        new ServerConfiguration("config.xml")
        {
            StartingGems = 69696969,
            StartingGold = 69696969,
            StartingElixir = 69696969
        };`
There already a declared value of gold,gems here so we don't need those lines :
`                StartingGems = _default.StartingGems;
                StartingGold = _default.StartingGold;
                StartingElixir = _default.StartingElixir;
`
Remove them and everything will be fine

**Comment by knightking10** [comment]
Fixed version by me [here](https://github.com/knightking10/CoCSharp/commit/c6deefe9e88e1751a69e44f781ba383295a4e0f9)
OR:
Create config.xml in bin/Debug with this content:

``` xml
<?xml version="1.0" encoding="utf-8"?>
<server_config>
  <starting_gems>69696969</starting_gems>
  <starting_gold>6969696</starting_gold>
  <starting_elixir>69696969</starting_elixir>
</server_config>
```

Good luck!
