### ISSUE TITLE
Problem with me ?

### ISSUE THREAD

**Issue by ghost** [FICTURE7/CoCSharp#92]
I wan't to help you,
And you censure me ?
Why ?
You have a problem with me ?
I just want to help you it's not a problem no ?

**Comment by FICTURE7** [comment]
Your previous issue, was useless. You brought nothing new to the table.  And those weren't fixing any bugs or anything like that. And those were only warnings that anyone knows about by simply compiling the project.

And I have nothing against you. ;]

**Comment by knightking10** [comment]
lol

**Comment by fivedashthree** [comment]
Hi TokyoSU,

While it's nice that you're trying to help with the project, as FICTURE7 said, you're not really "bringing anything to the table". The previous issue you posted was not very useful to the project, it only highlighed warning that would already show up in Visual Studio anyway. Compiler warnings can usually be ignored as they do not cause problems. 

Additionally, your only other contribution on your GitHub profile was a nasty comment on somebody's issue page, showing the sort of toxic additude that doesn't help anybody. 

If you are interested in helping the project, please, first, read the code and understand what it is, then if you want to you can bring up a mroe important issue.
