### ISSUE TITLE
SC Public Key?

### ISSUE THREAD

**Issue by tc-maxx** [FICTURE7/CoCSharp#99]
Hi,

where can i get the latest SuperCellPublicKey (v.8.709.16) to run the CocProxy?

Thank you!
Maxx

**Comment by FICTURE7** [comment]
You can retrieve them from the `libg.so` files.

**Comment by tc-maxx** [comment]
Hi ,could it be thats the key is stored at the beginning of the .data section:

![grafik](https://cloud.githubusercontent.com/assets/17054281/22185035/f2742ee6-e0dd-11e6-8930-45031c983c81.png)

4102C28189897A48CEDFA8C6E5378F55624F9E8408FA8A376643DBBCE715B21A

Thank you
Maxx

EDIT: yes it is the correct key.

**Comment by FICTURE7** [comment]
>Thank you

No need to thank me, you did all of the work yourself. XD
